import fs from 'fs';

const generateFile = async () => {
  const file = 'providers-list.json';
  const rawData = fs.readFileSync(file);
  const categories = JSON.parse(rawData.toString());

  let output =
    '/*GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.*/\n\n\nimport {ANIME, BOOKS, MANGA, COMICS, LIGHT_NOVELS, MOVIES} from \'@consumet/extensions\'\nimport fs from "fs"\nimport {performance} from "perf_hooks"\n\n';
  output += 'const start = async() => {\n';
  output +=
    " let output = '| **provider** | **Status** | **Time** |\\n|:--------:|:------:|:----:|\\n'\n";
  output += ' let t0, t1 = performance.now()\n';
  for (const category of categories) {
    const k = Object.keys(category)[0];

    for (const provider of category[k]) {
      const className = provider.classPath.split('.').slice(-1)[0];
      let query = '';
      switch (className) {
        case 'NineAnime':
        case 'Gogoanime':
        case 'MangaDex':
        case 'ReadLightNovels':
          query = 'One Piece';
          break;
        case 'Libgen':
        case 'ZLibrary':
          query = 'One Hundred Years of Solitude';
          break;
        case 'GetComics':
          query = 'batman';
      }

      let inFile = '	const ' + className + ' = new ';
      inFile += provider.classPath;
      inFile += '()\n';
      inFile += ' try {\n';
      inFile += '	t0 = performance.now()\n';
      inFile += `	 const ${className}Res = await ${className}.search("${query}")\n`;
      inFile += '	 t1 = performance.now()\n';
      if (className == 'Libgen') {
        inFile += `	if (${className}Res){\n`;
        inFile += `		 output += \`${`| [\${${className}.name}](${provider.baseUrl}) | 🟢 200 | \${((t1 - t0) / 1000).toPrecision(3)}s |\\n\``}\n`;
        inFile += '	}\n';
        inFile += `	else {\n`;
        inFile += `		 output += \`${`| [\${${className}.name}](${provider.baseUrl}) | 🔴 500 | \${((t1 - t0) / 1000).toPrecision(3)}s |\\n\``}\n`;
        inFile += '	}\n';
      } else if (className == 'GetComics') {
        inFile += `	if (${className}Res.containers){\n`;
        inFile += `		 output += \`${`| [\${${className}.name}](${provider.baseUrl}) | 🟢 200 | \${((t1 - t0) / 1000).toPrecision(3)}s |\\n\``}\n`;
        inFile += '	}\n';
        inFile += `	else {\n`;
        inFile += `		 output += \`${`| [\${${className}.name}](${provider.baseUrl}) | 🔴 500 | \${((t1 - t0) / 1000).toPrecision(3)}s |\\n\``}\n`;
        inFile += '	}\n';
      } else {
        inFile += `	if (${className}Res.results){\n`;
        inFile += `		 output += \`${`| [\${${className}.name}](${provider.baseUrl}) | 🟢 200 | \${((t1 - t0) / 1000).toPrecision(3)}s |\\n\``}\n`;
        inFile += '	}\n';
        inFile += `	else {\n`;
        inFile += `		 output += \`${`| [\${${className}.name}](${provider.baseUrl}) | 🔴 500 | \${((t1 - t0) / 1000).toPrecision(3)}s |\\n\``}\n`;
        inFile += '	}\n';
      }

      inFile += '} catch (e) {\n';
      inFile += `	 output += \`${`| [\${${className}.name}](${provider.baseUrl}) | 🔴 500 | 0s |\\n\``}\n`;
      inFile += '	}';
      output += inFile + '\n';
    }
  }
  output += "fs.writeFileSync('./README.md', output)";
  output += '}';
  output += '\n\n\n\nstart()';

  fs.writeFileSync('./chore-generator.ts', output);
};

(async () => {
  await generateFile();
})();
